### ISSUE TITLE
Is this repo is allowed to get featured on on awesome-github-profile-readmes?

### ISSUE THREAD

**Issue by abhisheknaiidu** [lauragift21/lauragift21#1]
Link : https://github.com/abhisheknaiidu/awesome-github-profile-readme

**Comment by lauragift21** [comment]
Hey @abhisheknaiidu! Yeah sure, you can add mine :)

**Comment by abhisheknaiidu** [comment]
> Hey @abhisheknaiidu! Yeah sure, you can add mine :)

Done and Don't forget to leave a ⭐ if you found this useful.
